apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: vitorir

images:
- name: goserver
  newName: vitoripiranga/gitops
  newTag: newtag
