apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: vitorir

images:
- name: goserver
  newName: vitoripiranga/gitopsfc
  newTag: e33303413b35cee0a1548503cce1f30a7be989d6
