name: CD Gitops

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    # Baixar o código do repositório do github
      - name: Checkout code
        uses: actions/checkout@v2
    
    # Buildar e publicar imagem no Docker Hub
      - name: Build and push image to Docker Hub
        run: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}
          repository: ${{ secrets.DOCKER_REPOSITORY}}/gitops
          tags: ${{ github.sha}}, latest
